name: Automatically generate README.rst

on: push

jobs:
  run-auto-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: run auto_readme.py
        run: python ./.github/workflows/auto_readme.py